version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      lint:
        patterns:
          - 'oxlint'
          - 'oxlint-tsgolint'
      monorepo:
        patterns:
          - 'turbo'
          - '@changesets/cli'
          - '@types/node'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
