name: Changeset PR Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changesets:
    uses: 4mbl/actions/.github/workflows/changeset-comment.yml@6d4ffb1e177ced1f08ee05b0df6a39ef8e231a1a # v1
