name: Changeset PR Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changesets:
    uses: 4mbl/actions/.github/workflows/changeset-comment.yml@96fa92ed0d4d9658bb2d050b5267307c9d9ee324 # v1
