name: Publish to npm - stable

on:
  release:
    types: [created]

env:
  # npm 11.5.1+ required for trusted publishing
  NODE_VERSION: '24.5.0'

jobs:
  publish-stable:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4

        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish
