name: Publish to npm

on:
  # beta release trigger
  push:
    branches:
      - main
  # stable release trigger
  release:
    types: [created]

env:
  # npm 11.5.1+ required for trusted publishing
  NODE_VERSION: '24.5.0'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to npm - beta
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          BETA_VERSION="0.0.0-beta.$SHORT_SHA"
          echo "Setting version to $BETA_VERSION"
          npm version "$BETA_VERSION" --no-git-tag-version
          npm publish --tag beta

      - name: Publish to npm - stable
        if: github.event_name == 'release' && github.event.action == 'created'
        run: npm publish
